### ISSUE TITLE
Test failures on Python 3 

### ISSUE THREAD

**Issue by rahulporuri** [enthought/codetools#35]
Three test failures are seen when installing codetools from pypi in a python 3 env. Note that some of the dependencies need to be installed manually as they are not specified in the codetools setup script. See #26 .

```
======================================================================
ERROR: Assigning floats to arrays
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rporuri/.edm/envs/temp3/lib/python3.6/site-packages/codetools/contexts/tests/with_mask_test_case.py", line 44, in test1
    file_object = open(os.path.join(self.code_dir,'test1.py'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/rporuri/.edm/envs/temp3/lib/python3.6/site-packages/codetools/contexts/tests/with_mask_codes/test1.py'

======================================================================
ERROR: Different sized arrays
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rporuri/.edm/envs/temp3/lib/python3.6/site-packages/codetools/contexts/tests/with_mask_test_case.py", line 65, in test2
    file_object = open(os.path.join(self.code_dir,'test2.py'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/rporuri/.edm/envs/temp3/lib/python3.6/site-packages/codetools/contexts/tests/with_mask_codes/test2.py'

======================================================================
ERROR: Same sized array assignments within 'with' block
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rporuri/.edm/envs/temp3/lib/python3.6/site-packages/codetools/contexts/tests/with_mask_test_case.py", line 86, in test3
    file_object = open(os.path.join(self.code_dir,'test3.py'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/rporuri/.edm/envs/temp3/lib/python3.6/site-packages/codetools/contexts/tests/with_mask_codes/test3.py'
```

The errors are because `.../with_mask_codes/` doesn't contain an `__init__` file so the `test*.py` files in the submodule aren't included in the sdist uploaded to pypi.

**Comment by rahulporuri** [comment]
This should be fixed along with #34
