### ISSUE TITLE
codetools.blocks.api not importable on Python 3

### ISSUE THREAD

**Issue by mdickinson** [enthought/codetools#38]
On Python 3 we have:
```
>>> import codetools.blocks.api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/.edm/envs/codetools/lib/python3.6/site-packages/codetools/blocks/api.py", line 10, in <module>
    from .analysis import NameFinder, free_vars, local_vars, conditional_local_vars
  File "/Users/mdickinson/.edm/envs/codetools/lib/python3.6/site-packages/codetools/blocks/analysis.py", line 10, in <module>
    import compiler, compiler.ast
ModuleNotFoundError: No module named 'compiler'
```

We should either fix the code (if that's possible), or at least fix things up so that the error message is more user friendly (e.g., a "sorry, codetools.blocks isn't supported on Python 3).

**Comment by mdickinson** [comment]
Same issue with `codetools.execution.api`.
