### ISSUE TITLE
Should `PersistableMixin` fall back to stdlib pickle library if `apptools` is not installed

### ISSUE THREAD

**Issue by rahulporuri** [enthought/codetools#45]
`codetools.contexts.data_context.DataContext` is one of the common reasons why other packages/applications use `codetools`. At the moment, needing a `DataContext` forces the user to install `apptools` because of the dependency of `PersistableMixin` on `apptools.sweet_pickle`.

https://github.com/enthought/codetools/blob/38b01bb6c9a79cc9e5de95c566c054b048e5697a/codetools/contexts/data_context.py#L194

https://github.com/enthought/codetools/blob/38b01bb6c9a79cc9e5de95c566c054b048e5697a/codetools/contexts/data_context.py#L227

To remove the strong dependency on `apptools`, should `PersistableMixin` simply fall back to using the pickle library in the standard library if `apptools` is not installed?

**Comment by coreysharris** [comment]
I'm not sure whether to open a separate issue for this, but now that [`sweet_pickle` has been removed](https://github.com/enthought/apptools/pull/199) from `apptools`, even installing `apptools` is not enough.

```
❯ edm install -e test-env codetools apptools      
No value provided for --version. Assuming 3.6
Fetching indices for runtime repositories. done
Fetching indices for package repositories.......... done
Fetching indices for runtime repositories. done
Installing runtime... done

The following packages will be installed:

    appdirs              1.4.3-1         15     KiB
    apptools             5.1.0-1        464     KiB
    codetools            4.3.0-11       370     KiB
    configobj            5.0.6.post9-1   72     KiB
    distribute_remove    1.0.0-4          2     KiB
    importlib_metadata   2.0.0-1         59     KiB
    importlib_resources  3.3.0-1         58     KiB
    packaging            16.8-4          46     KiB
    pip                  20.0.2-3         2.7   MiB
    pyface               7.2.0-1          2.21  MiB
    pyparsing            2.2.0-1        125     KiB
    setuptools           41.6.0-4         1     MiB
    six                  1.15.0-1        23     KiB
    traits               6.1.1-1          1.01  MiB
    traitsui             7.1.1-2          2.51  MiB
    zipp                 3.4.0-2         10     KiB

Do you want to continue ? [Y/n]: 
Installing/removing package(s)
apptools            [...............................................................................................................................................]

To use this environment, please use the following command::

    $ edm shell --environment test-env

You can exit that environment at anytime by typing::

    $ exit

❯ edm run -e test-env -- python -c 'from codetools.contexts.data_context import DataContext'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/charris/.edm/envs/test-env/lib/python3.6/site-packages/codetools/contexts/data_context.py", line 18, in <module>
    from apptools import sweet_pickle
ImportError: cannot import name 'sweet_pickle'
```

**Comment by rahulporuri** [comment]
This is a high priority as it prevents applications which depend on `DataContext` from even launching.
